# Generated by Django 2.1.1 on 2018-09-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='preData',
            fields=[
                ('user', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('msg', models.CharField(max_length=128)),
            ],
        ),
    ]
